//+------------------------------------------------------------------+
//|                                     NatGas_Strategy_v6.8.mq5     |
//|                                     Generated by Gemini AI       |
//|                             "Trend Trailing Version"             |
//|      Base: v6.7 (High/Low prices added)                          |
//|      Fix: Added High-Low 'Points' calculation to S2 Data Miner   |
//+------------------------------------------------------------------+
#property copyright "Gemini AI"
#property link      ""
#property version   "6.8"

#include <Trade\Trade.mqh>

//--- Strategy Selection Enum
enum ENUM_STRATEGY_ACTIVE
  {
   STRATEGY_ALL = 0,           // Run ALL Strategies
   STRATEGY_1 = 1,             // Run Strategy 1 Only (Stoch Trend)
   STRATEGY_2 = 2,             // Run Strategy 2 Only (BB Mean Reversion)
   STRATEGY_3 = 3,             // Run Strategy 3 Only (EMA Gap Trend)
   STRATEGY_4 = 4              // Run Strategy 4 Only (Price Action Engulfing)
  };

//--- Miner Timeframe Enum
enum ENUM_MINER_TF
  {
   TF_M5 = PERIOD_M5,      // 5 Minutes
   TF_M15 = PERIOD_M15,    // 15 Minutes
   TF_H1 = PERIOD_H1,      // 1 Hour
   TF_H4 = PERIOD_H4       // 4 Hours
  };

//--- Input Parameters
input group "=== Strategy & Risk ==="
input bool     InpEnableTrading = true;        // Master Toggle: Enable Trading Strategies
input ENUM_STRATEGY_ACTIVE InpStrategyActive = STRATEGY_1; // Active Strategy Mode
input int      InpMagic        = 123456;       // Base Magic Number

input group "=== Lot Size & Limits ==="
input double   InpLots         = 0.12;         // Base Lot Size (High Performance Setting)

input group "=== Days to Trade ==="
input bool     InpTradeMonday    = true;       // Trade on Monday
input bool     InpTradeTuesday   = true;       // Trade on Tuesday
input bool     InpTradeWednesday = true;       // Trade on Wednesday
input bool     InpTradeThursday  = true;       // Trade on Thursday
input bool     InpTradeFriday    = true;       // Trade on Friday

input group "=== Time Filter Settings ==="
input bool     InpUseTimeFilter = true;        // Restrict trading to specific hours (Recommended)
input int      InpStartHour     = 6;           // Start Trading (Server Hour 0-23)
input int      InpEndHour       = 23;          // Stop Trading (Server Hour 0-23)

input group "=== Friday Gap Protection ==="
input bool     InpUseFridayLogic      = false; // Enable Friday Anti-Gap Logic
input int      InpFridayStopEntryHour = 21;    // Stop New Entries (Hour) - allows NY session
input int      InpFridayCloseAllHour  = 22;    // Close All Positions (Hour) - escapes the gap

input group "=== Strategy 1: Trend Momentum ==="
input int      InpTP_Trend     = 100;          // Trend Take Profit (Points)
input int      InpSL_Trend     = 150;          // Trend Stop Loss (Points)
input int      InpTrend_MaxDist= 5;           // Max allowed distance from EMA20 to enter
input int      InpTrend_MaxDist_EMA50 = 10;    // Max allowed distance from EMA50 to enter
input double   InpMinEmaSpread_S1 = 0.0020;    // MINIMUM EMA SPREAD (Loosened to allow early breakouts)

// Trailing Stop for Strat 1
input bool     InpUseTrailing_S1 = true;       // Enable Trailing for Strategy 1
input int      InpTrailing_Start_S1 = 30;      // Start trailing after X points profit
input int      InpTrailing_Dist_S1 = 25;       // Trail X points behind price

// Stoch Settings (Shared)
input int      InpStoch_K      = 14;           // Stochastic K Period
input int      InpStoch_D      = 3;            // Stochastic D Period
input int      InpStoch_Slow   = 3;            // Stochastic Slowing
input double   InpStoch_Dist   = 5.0;          // Stochastic: Min Spread

input double   InpStoch_Buy_Min  = 20.0;       // Stoch Lower Limit for Buy
input double   InpStoch_Buy_Max  = 80.0;       // Stoch Upper Limit for Buy
input double   InpStoch_Sell_Min = 20.0;       // Stoch Lower Limit for Sell
input double   InpStoch_Sell_Max = 80.0;       // Stoch Upper Limit for Sell

input group "=== RSI Filter (Shared) ==="
input bool     InpUseRSI_Filter  = true;       // Trade only if RSI agrees with direction
input double   InpRSI_Center     = 50.0;       // Buy > 50, Sell < 50
input int      InpRSI_Period     = 14;         // RSI Period

input group "=== Strategy 2: Bollinger Settings ==="
input int      InpTP_BBRule    = 50;           // BB Strat: Take Profit
input int      InpSL_BBRule    = 50;           // BB Strat: Stop Loss
input int      InpBands_Period = 20;           // BB Period
input double   InpBands_Dev    = 2.5;          // BB Deviation
input int      InpBands_Shift  = 0;            // BB Shift
input double   InpRSI_BuyLvl   = 25.0;         // BB Strat: Buy if RSI < X
input double   InpRSI_SellLvl  = 75.0;         // BB Strat: Sell if RSI > X

input group "=== Strategy 3: EMA Settings ==="
input int      InpTP_Strat3    = 200;          // EMA Strat: Take Profit
input int      InpSafetySL_Strat3 = 100;       // EMA Strat: Safety SL
input int      InpTrailing_Strat3 = 50;        // EMA Strat: Trailing Stop
input double   InpMinDist_Strat3  = 0.0020;    // EMA Strat: Min EMA Distance

input group "=== Strategy 4: Price Action ==="
input int      InpTP_Strat4    = 100;          // PA Strat: Take Profit
input int      InpSL_Strat4    = 50;           // PA Strat: Stop Loss

input group "=== Shared Indicators ==="
input int      InpEMA20_Period = 20;           // EMA Fast Period
input int      InpEMA50_Period = 50;           // EMA Slow Period

input group "=== Diagnostics & Logging === Strategy 1"
input bool     InpLogAllCandles = false;       // Record "NO TRADE" candles to CSV for Data Mining

input group "=== Strategy 2: Data Miner ==="
input bool          InpRunS2Miner = false;      // Enable S2 Data Miner
input ENUM_MINER_TF InpMinerTF    = TF_M15;     // Miner Timeframe

//--- Global Variables
CTrade         trade;
int            handle_EMA20;
int            handle_EMA50;
int            handle_Stoch;
int            handle_Bands; 
int            handle_RSI;
string         tradeSymbol;
datetime       lastBarTime = 0; 
string         csvFilename = ""; 

//--- Strategy 2 Data Miner Variables
int            handle_EMA20_S2;
int            handle_EMA50_S2;
int            handle_Stoch_S2;
int            handle_Bands_S2; 
int            handle_RSI_S2;
datetime       lastBarTime_S2 = 0;
string         csvFilename_S2 = "";

//--- Statistics Variables
int    stat_S1_Total = 0; int stat_S1_Wins = 0; int stat_S1_Loss = 0; double stat_S1_PL = 0.0;

//--- Trade Memory Struct for Synchronous Diagnostics
struct TradeMemory
  {
   ulong    ticket;
   long     type;
   datetime entryTime;
   double   ema20;
   double   ema50;
   double   stochK;
   double   stochD;
   double   rsi;
   long     tickVol;
   bool     active;
  };
TradeMemory activeTrades[];

//+------------------------------------------------------------------+
//| Helper: Format Double for European Excel (Replaces . with ,)     |
//+------------------------------------------------------------------+
string D2S(double value, int digits)
  {
   string str = DoubleToString(value, digits);
   StringReplace(str, ".", ","); // Convert decimal point to comma for Excel
   return str;
  }

//+------------------------------------------------------------------+
//| Helper: Get Day String                                           |
//+------------------------------------------------------------------+
string GetDayStr(int day_of_week)
  {
   switch(day_of_week)
     {
      case 0: return "Sunday";
      case 1: return "Monday";
      case 2: return "Tuesday";
      case 3: return "Wednesday";
      case 4: return "Thursday";
      case 5: return "Friday";
      case 6: return "Saturday";
     }
   return "Unknown";
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   tradeSymbol = _Symbol;
   
   Print(">>> EA INITIALIZING (v6.8) on chart: ", tradeSymbol); 
   
   long hwid = AccountInfoInteger(ACCOUNT_LOGIN);
   ulong msCount = GetMicrosecondCount(); 
   
   // --- STRATEGY 1 CSV INITIALIZATION ---
   if(InpEnableTrading)
     {
      csvFilename = "Strategy1_Log_v6.8_" + IntegerToString(hwid) + "_" + IntegerToString(msCount) + ".csv";
      Print(">> Strat 1 CSV Logger initialized: ", csvFilename);

      int file = FileOpen(csvFilename, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file != INVALID_HANDLE)
        {
         FileWrite(file, "Ticket", "Type", "Result", "Profit_Loss", "EntryDate", "ExitDate", "EntryDay", "ExitDay", "EntryTime", "ExitTime", "EMA20", "EMA50", "StochK", "StochD", "RSI", "TickVol");
         FileClose(file);
        }

      // Strategy 1 Indicators (Strictly M15)
      handle_EMA20 = iMA(tradeSymbol, PERIOD_M15, InpEMA20_Period, 0, MODE_EMA, PRICE_CLOSE); 
      handle_EMA50 = iMA(tradeSymbol, PERIOD_M15, InpEMA50_Period, 0, MODE_EMA, PRICE_CLOSE);
      handle_Stoch = iStochastic(tradeSymbol, PERIOD_M15, InpStoch_K, InpStoch_D, InpStoch_Slow, MODE_SMA, STO_LOWHIGH);
      handle_Bands = iBands(tradeSymbol, PERIOD_M15, 20, 0, 2.0, PRICE_CLOSE);
      handle_RSI   = iRSI(tradeSymbol, PERIOD_M15, InpRSI_Period, PRICE_CLOSE);

      if(handle_EMA20 == INVALID_HANDLE || handle_EMA50 == INVALID_HANDLE || 
         handle_Stoch == INVALID_HANDLE || handle_Bands == INVALID_HANDLE || 
         handle_RSI == INVALID_HANDLE)
        {
         Print("Error creating indicator handles.");
         return(INIT_FAILED);
        }
     }

   // --- STRATEGY 2 DATA MINER INITIALIZATION ---
   if(InpRunS2Miner)
     {
      string tfStr = EnumToString(InpMinerTF);
      StringReplace(tfStr, "TF_", ""); // Clean up name (e.g. TF_M5 -> M5)
      
      csvFilename_S2 = "Strat2_DataMiner_" + tfStr + "_" + IntegerToString(hwid) + "_" + IntegerToString(msCount) + ".csv";
      Print(">> Strat 2 Data Miner CSV initialized: ", csvFilename_S2);

      int fileS2 = FileOpen(csvFilename_S2, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(fileS2 != INVALID_HANDLE)
        {
         FileWrite(fileS2, "Date", "Time", "Price_Open", "Price_High", "Price_Low", "Points", "Price_Close", "Day", "EMA20", "EMA50", "Stoch_K", "Stoch_D", "RSI", "BB_Upper", "BB_Lower", "Volume");
         FileClose(fileS2);
        }
        
      // Initialize completely separate handles based on selected timeframe
      ENUM_TIMEFRAMES minerEnumTF = (ENUM_TIMEFRAMES)InpMinerTF;
      handle_EMA20_S2 = iMA(tradeSymbol, minerEnumTF, InpEMA20_Period, 0, MODE_EMA, PRICE_CLOSE);
      handle_EMA50_S2 = iMA(tradeSymbol, minerEnumTF, InpEMA50_Period, 0, MODE_EMA, PRICE_CLOSE);
      handle_Stoch_S2 = iStochastic(tradeSymbol, minerEnumTF, InpStoch_K, InpStoch_D, InpStoch_Slow, MODE_SMA, STO_LOWHIGH);
      handle_Bands_S2 = iBands(tradeSymbol, minerEnumTF, InpBands_Period, InpBands_Shift, InpBands_Dev, PRICE_CLOSE);
      handle_RSI_S2   = iRSI(tradeSymbol, minerEnumTF, InpRSI_Period, PRICE_CLOSE);
     }

   trade.SetExpertMagicNumber(InpMagic);
   trade.LogLevel(LOG_LEVEL_NO); 
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(InpEnableTrading)
     {
      PrintFormat("FINAL STATS: Strategy 1 [Total:%d | W:%d | L:%d | PL:%.2f]", stat_S1_Total, stat_S1_Wins, stat_S1_Loss, stat_S1_PL);
      IndicatorRelease(handle_EMA20); IndicatorRelease(handle_EMA50);
      IndicatorRelease(handle_Stoch); 
      IndicatorRelease(handle_Bands); IndicatorRelease(handle_RSI);
     }
               
   Comment("");
   
   if(InpRunS2Miner)
     {
      IndicatorRelease(handle_EMA20_S2); IndicatorRelease(handle_EMA50_S2);
      IndicatorRelease(handle_Stoch_S2); IndicatorRelease(handle_Bands_S2);
      IndicatorRelease(handle_RSI_S2);
     }
  }

//+------------------------------------------------------------------+
//| Helper: Strategy 2 Data Miner Logic (Totally Isolated)           |
//+------------------------------------------------------------------+
void RunStrategy2Miner()
  {
   if(!InpRunS2Miner) return;

   ENUM_TIMEFRAMES activeTF = (ENUM_TIMEFRAMES)InpMinerTF;
   datetime currBarTime_S2 = iTime(tradeSymbol, activeTF, 0);
   if(currBarTime_S2 == 0) return; // Wait for historical data
   
   if(lastBarTime_S2 == 0)
     {
      lastBarTime_S2 = currBarTime_S2;
      return;
     }
     
   // Triggers exactly when a new bar forms on your selected timeframe
   if(currBarTime_S2 != lastBarTime_S2)
     {
      datetime closedBarTime = iTime(tradeSymbol, activeTF, 1);
      
      double open[1], high[1], low[1], close[1], ema20[1], ema50[1], stochK[1], stochD[1], rsi[1], upper[1], lower[1];
      long tickVol[1];
      
      // Fetch data specifically for index 1 (the fully closed candle)
      if(CopyOpen(tradeSymbol, activeTF, 1, 1, open) != 1) return;
      if(CopyHigh(tradeSymbol, activeTF, 1, 1, high) != 1) return;
      if(CopyLow(tradeSymbol, activeTF, 1, 1, low) != 1) return;
      if(CopyClose(tradeSymbol, activeTF, 1, 1, close) != 1) return;
      if(CopyTickVolume(tradeSymbol, activeTF, 1, 1, tickVol) != 1) return;
      
      if(CopyBuffer(handle_EMA20_S2, 0, 1, 1, ema20) != 1) return;
      if(CopyBuffer(handle_EMA50_S2, 0, 1, 1, ema50) != 1) return;
      if(CopyBuffer(handle_Stoch_S2, 0, 1, 1, stochK) != 1) return;
      if(CopyBuffer(handle_Stoch_S2, 1, 1, 1, stochD) != 1) return;
      if(CopyBuffer(handle_RSI_S2, 0, 1, 1, rsi) != 1) return;
      if(CopyBuffer(handle_Bands_S2, 1, 1, 1, upper) != 1) return;
      if(CopyBuffer(handle_Bands_S2, 2, 1, 1, lower) != 1) return;
      
      // Calculate total points for the candle
      double point_val = SymbolInfoDouble(tradeSymbol, SYMBOL_POINT);
      long pointsDiff = (long)MathRound((high[0] - low[0]) / point_val);
      
      // Format timestamps
      MqlDateTime tm;
      TimeToStruct(closedBarTime, tm);
      string dayStr = GetDayStr(tm.day_of_week);
      string dateStr = TimeToString(closedBarTime, TIME_DATE); StringReplace(dateStr, ".", "/");
      string timeStr = TimeToString(closedBarTime, TIME_MINUTES); StringReplace(timeStr, ":", ".");
      
      // Append strictly to S2 CSV
      int file = FileOpen(csvFilename_S2, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file != INVALID_HANDLE)
        {
         FileSeek(file, 0, SEEK_END);
         FileWrite(file, dateStr, timeStr, D2S(open[0], 4), D2S(high[0], 4), D2S(low[0], 4), IntegerToString(pointsDiff), D2S(close[0], 4), dayStr,
                   D2S(ema20[0], 4), D2S(ema50[0], 4), D2S(stochK[0], 2), D2S(stochD[0], 2),
                   D2S(rsi[0], 2), D2S(upper[0], 4), D2S(lower[0], 4), IntegerToString(tickVol[0]));
         FileClose(file);
        }
        
      lastBarTime_S2 = currBarTime_S2;
     }
  }

//+------------------------------------------------------------------+
//| Helper: Check Trading Time & Days                                |
//+------------------------------------------------------------------+
bool IsTradingTime()
  {
   datetime currentTime = TimeCurrent();
   MqlDateTime tm;
   TimeToStruct(currentTime, tm);
   
   if(tm.day_of_week == 1 && !InpTradeMonday) return(false);
   if(tm.day_of_week == 2 && !InpTradeTuesday) return(false);
   if(tm.day_of_week == 3 && !InpTradeWednesday) return(false);
   if(tm.day_of_week == 4 && !InpTradeThursday) return(false);
   if(tm.day_of_week == 5 && !InpTradeFriday) return(false);
   
   if(InpUseFridayLogic && tm.day_of_week == 5 && tm.hour >= InpFridayStopEntryHour) return(false);
     
   if(!InpUseTimeFilter) return(true); 
   if(tm.hour >= InpStartHour && tm.hour < InpEndHour) return(true);
   
   return(false);
  }

//+------------------------------------------------------------------+
//| Helper: Friday Anti-Gap Protection                               |
//+------------------------------------------------------------------+
void CheckFridayClose()
  {
   if(!InpUseFridayLogic) return;
   
   MqlDateTime tm;
   TimeToStruct(TimeCurrent(), tm);
   
   if(tm.day_of_week == 5 && tm.hour >= InpFridayCloseAllHour)
     {
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i);
         if(PositionSelectByTicket(ticket))
           {
            if(PositionGetString(POSITION_SYMBOL) == tradeSymbol) trade.PositionClose(ticket);
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Helper: Synchronous Diagnostic CSV Logger                        |
//+------------------------------------------------------------------+
bool IsTracked(ulong ticket)
  {
   for(int i = 0; i < ArraySize(activeTrades); i++)
     {
      if(activeTrades[i].active && activeTrades[i].ticket == ticket) return true;
     }
   return false;
  }

void TrackNewTrade(ulong ticket, long type, datetime entryTime, double ema20, double ema50, double stochK, double stochD, double rsi, long tickVol)
  {
   int size = ArraySize(activeTrades);
   for(int i = 0; i < size; i++)
     {
      if(!activeTrades[i].active)
        {
         activeTrades[i].ticket = ticket; activeTrades[i].type = type; activeTrades[i].entryTime = entryTime;
         activeTrades[i].ema20 = ema20; activeTrades[i].ema50 = ema50; activeTrades[i].stochK = stochK;
         activeTrades[i].stochD = stochD; activeTrades[i].rsi = rsi; activeTrades[i].tickVol = tickVol;
         activeTrades[i].active = true;
         return;
        }
     }
   ArrayResize(activeTrades, size + 1);
   activeTrades[size].ticket = ticket; activeTrades[size].type = type; activeTrades[size].entryTime = entryTime;
   activeTrades[size].ema20 = ema20; activeTrades[size].ema50 = ema50; activeTrades[size].stochK = stochK;
   activeTrades[size].stochD = stochD; activeTrades[size].rsi = rsi; activeTrades[size].tickVol = tickVol;
   activeTrades[size].active = true;
  }

bool ProcessClosedTrade(TradeMemory &mem)
  {
   HistorySelect(0, TimeCurrent());
   double profit = 0; datetime exitTime = 0; bool found = false;
   int total = HistoryDealsTotal();
   for(int i = total - 1; i >= 0; i--)
     {
      ulong dealTicket = HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(dealTicket, DEAL_POSITION_ID) == mem.ticket)
        {
         if(HistoryDealGetInteger(dealTicket, DEAL_ENTRY) == DEAL_ENTRY_OUT)
           {
            profit += HistoryDealGetDouble(dealTicket, DEAL_PROFIT) + HistoryDealGetDouble(dealTicket, DEAL_SWAP) + HistoryDealGetDouble(dealTicket, DEAL_COMMISSION);
            exitTime = (datetime)HistoryDealGetInteger(dealTicket, DEAL_TIME);
            found = true; break;
           }
        }
     }

   if(!found) return false; 
   
   string resultStr = (profit > 0) ? "Win" : "Loss";
   string typeStr = (mem.type == POSITION_TYPE_BUY) ? "Buy" : "Sell";
   stat_S1_Total++;
   if(profit > 0) stat_S1_Wins++; else stat_S1_Loss++;
   stat_S1_PL += profit;
   
   MqlDateTime inTm; TimeToStruct(mem.entryTime, inTm); string inDay = GetDayStr(inTm.day_of_week);
   string inDate = TimeToString(mem.entryTime, TIME_DATE); StringReplace(inDate, ".", "/");
   string inTime = TimeToString(mem.entryTime, TIME_MINUTES); StringReplace(inTime, ":", ".");

   MqlDateTime outTm; TimeToStruct(exitTime, outTm); string outDay = GetDayStr(outTm.day_of_week);
   string outDate = TimeToString(exitTime, TIME_DATE); StringReplace(outDate, ".", "/");
   string outTime = TimeToString(exitTime, TIME_MINUTES); StringReplace(outTime, ":", ".");

   int file = FileOpen(csvFilename, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
   if(file != INVALID_HANDLE)
     {
      FileSeek(file, 0, SEEK_END);
      FileWrite(file, IntegerToString(mem.ticket), typeStr, resultStr, D2S(profit, 2), 
                inDate, outDate, inDay, outDay, inTime, outTime,
                D2S(mem.ema20, 4), D2S(mem.ema50, 4), D2S(mem.stochK, 2), D2S(mem.stochD, 2), D2S(mem.rsi, 2), IntegerToString(mem.tickVol));
      FileClose(file);
     }
   return true;
  }

//+------------------------------------------------------------------+
//| Helper: Market Data Logger (Logs Every M15 Candle)               |
//+------------------------------------------------------------------+
void LogMarketData(datetime barTime, double ema20, double ema50, double stochK, double stochD, double rsi, long tickVol)
  {
   if(!InpLogAllCandles) return; 

   MqlDateTime tm; TimeToStruct(barTime, tm);
   string dayStr = GetDayStr(tm.day_of_week);
   string dateStr = TimeToString(barTime, TIME_DATE); StringReplace(dateStr, ".", "/");
   string timeStr = TimeToString(barTime, TIME_MINUTES); StringReplace(timeStr, ":", ".");

   int file = FileOpen(csvFilename, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
   if(file != INVALID_HANDLE)
     {
      FileSeek(file, 0, SEEK_END);
      FileWrite(file, "", "", "NO TRADE", "", dateStr, "", dayStr, "", timeStr, "", 
                D2S(ema20, 4), D2S(ema50, 4), D2S(stochK, 2), D2S(stochD, 2), D2S(rsi, 2), IntegerToString(tickVol));
      FileClose(file);
     }
  }

//+------------------------------------------------------------------+
//| Helper: Trailing Stop for Strategy 1                             |
//+------------------------------------------------------------------+
void CheckTrailingStop_S1(double point, int digits)
{
   if(!InpUseTrailing_S1) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionSelectByTicket(PositionGetTicket(i)))
      {
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol && PositionGetInteger(POSITION_MAGIC) == (InpMagic + 1))
         {
            ulong ticket = PositionGetInteger(POSITION_TICKET);
            long type = PositionGetInteger(POSITION_TYPE);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentTP = PositionGetDouble(POSITION_TP);

            if(type == POSITION_TYPE_BUY)
            {
               double bid = SymbolInfoDouble(tradeSymbol, SYMBOL_BID);
               if((bid - openPrice) >= InpTrailing_Start_S1 * point)
               {
                  double newSL = NormalizeDouble(bid - (InpTrailing_Dist_S1 * point), digits);
                  if(newSL >= currentSL + (10 * point)) trade.PositionModify(ticket, newSL, currentTP);
               }
            }
            else if(type == POSITION_TYPE_SELL)
            {
               double ask = SymbolInfoDouble(tradeSymbol, SYMBOL_ASK);
               if((openPrice - ask) >= InpTrailing_Start_S1 * point)
               {
                  double newSL = NormalizeDouble(ask + (InpTrailing_Dist_S1 * point), digits);
                  if(currentSL == 0 || newSL <= currentSL - (10 * point)) trade.PositionModify(ticket, newSL, currentTP);
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Helper: Trailing Stop (Strat 3)                                  |
//+------------------------------------------------------------------+
void CheckTrailingStop(double point, int digits)
  {
   if(InpTrailing_Strat3 <= 0) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionSelectByTicket(PositionGetTicket(i)))
        {
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol && PositionGetInteger(POSITION_MAGIC) == (InpMagic + 3)) 
           {
            ulong ticket = PositionGetInteger(POSITION_TICKET);
            double currentSL = PositionGetDouble(POSITION_SL);
            
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
              {
               double currentPrice = SymbolInfoDouble(tradeSymbol, SYMBOL_BID);
               double proposedSL = currentPrice - (InpTrailing_Strat3 * point);
               if(proposedSL > currentSL && (currentPrice - proposedSL) >= (InpTrailing_Strat3 * point))
                 {
                  double newSL = NormalizeDouble(proposedSL, digits);
                  trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                 }
              }
            else if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
              {
               double currentPrice = SymbolInfoDouble(tradeSymbol, SYMBOL_ASK);
               double proposedSL = currentPrice + (InpTrailing_Strat3 * point);
               if((proposedSL < currentSL || currentSL == 0) && (proposedSL - currentPrice) >= (InpTrailing_Strat3 * point))
                 {
                  double newSL = NormalizeDouble(proposedSL, digits);
                  trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
                 }
              }
           }
        }
     }
  }

void CheckStrategy3Exits(double closePrice, double ema20Value)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionSelectByTicket(PositionGetTicket(i)))
        {
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol && PositionGetInteger(POSITION_MAGIC) == (InpMagic + 3))
           {
            ulong ticket = PositionGetInteger(POSITION_TICKET);
            long type = PositionGetInteger(POSITION_TYPE);
            
            if(type == POSITION_TYPE_BUY && closePrice < ema20Value) trade.PositionClose(ticket);
            else if(type == POSITION_TYPE_SELL && closePrice > ema20Value) trade.PositionClose(ticket);
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // --- 0. Strategy 2 Data Miner (Isolated Execution) ---
   RunStrategy2Miner();
   
   if(!InpEnableTrading) return; // <-- MASTER TOGGLE: Bypass all trading logic if Miner-only
   
   // --- 1. Friday Anti-Gap Protection ---
   CheckFridayClose();

   // --- 2. Get Strategy 1/Core Indicator Data ---
   double ema20[], ema50[], stochK[], stochD[], rsiVal[], upperBand[], lowerBand[];
   double openPrices[], closePrices[];
   long tickVol[];
   
   ArraySetAsSeries(ema20, true); ArraySetAsSeries(ema50, true);
   ArraySetAsSeries(stochK, true); ArraySetAsSeries(stochD, true);
   ArraySetAsSeries(upperBand, true); ArraySetAsSeries(lowerBand, true);
   ArraySetAsSeries(rsiVal, true); 
   ArraySetAsSeries(openPrices, true); ArraySetAsSeries(closePrices, true);
   ArraySetAsSeries(tickVol, true);

   if(CopyBuffer(handle_EMA20, 0, 0, 4, ema20) != 4) return;
   if(CopyBuffer(handle_EMA50, 0, 0, 4, ema50) != 4) return;
   if(CopyBuffer(handle_Stoch, 0, 0, 4, stochK) != 4) return;      
   if(CopyBuffer(handle_Stoch, 1, 0, 4, stochD) != 4) return; 
   if(CopyBuffer(handle_Bands, 1, 0, 2, upperBand) != 2) return; 
   if(CopyBuffer(handle_Bands, 2, 0, 2, lowerBand) != 2) return; 
   if(CopyBuffer(handle_RSI, 0, 0, 2, rsiVal) != 2) return;
   if(CopyOpen(tradeSymbol, PERIOD_M15, 0, 4, openPrices) != 4) return;
   if(CopyClose(tradeSymbol, PERIOD_M15, 0, 4, closePrices) != 4) return;
   if(CopyTickVolume(tradeSymbol, PERIOD_M15, 0, 2, tickVol) != 2) return;

   double bid = SymbolInfoDouble(tradeSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(tradeSymbol, SYMBOL_ASK);
   double point = SymbolInfoDouble(tradeSymbol, SYMBOL_POINT);
   int digits = (int)SymbolInfoInteger(tradeSymbol, SYMBOL_DIGITS);

   double currEMA20 = ema20[0]; double currEMA50 = ema50[0];
   double currK = stochK[0];    double currD = stochD[0];
   double currRSI = rsiVal[0];
   long currTickVol = tickVol[0];
   double distStoch = MathAbs(currK - currD);
   double distPrice_EMA20 = MathAbs(bid - currEMA20) / point; 
   double distPrice_EMA50 = MathAbs(bid - currEMA50) / point; 
   
   // --- SYNCHRONOUS DIAGNOSTIC TRACKER (Exit Check) ---
   for(int i = 0; i < ArraySize(activeTrades); i++)
     {
      if(activeTrades[i].active)
        {
         if(!PositionSelectByTicket(activeTrades[i].ticket))
           {
            if(ProcessClosedTrade(activeTrades[i])) activeTrades[i].active = false;
           }
        }
     }

   // Common update & New Bar Check
   datetime currBarTime = iTime(tradeSymbol, PERIOD_M15, 0);
   bool isNewBar = (currBarTime != lastBarTime);
   
   // --- MANAGEMENT LOGIC (Exit Checks & Data Logging) ---
   if(isNewBar && lastBarTime != 0)
     {
      datetime closedBarTime = iTime(tradeSymbol, PERIOD_M15, 1);
      LogMarketData(closedBarTime, ema20[1], ema50[1], stochK[1], stochD[1], rsiVal[1], tickVol[1]);

      if(InpStrategyActive == STRATEGY_3 || InpStrategyActive == STRATEGY_ALL)
        {
         CheckStrategy3Exits(closePrices[1], currEMA20);
        }
     }
     
   // --- EVERY TICK MANAGEMENT ---
   CheckTrailingStop_S1(point, digits); 
   if(InpStrategyActive == STRATEGY_3 || InpStrategyActive == STRATEGY_ALL) CheckTrailingStop(point, digits);

   bool runStrat1 = (InpStrategyActive == STRATEGY_ALL || InpStrategyActive == STRATEGY_1);
   bool runStrat2 = (InpStrategyActive == STRATEGY_ALL || InpStrategyActive == STRATEGY_2);
   bool runStrat3 = (InpStrategyActive == STRATEGY_ALL || InpStrategyActive == STRATEGY_3);
   bool runStrat4 = (InpStrategyActive == STRATEGY_ALL || InpStrategyActive == STRATEGY_4);

   bool isS1Open = false; bool isBBOpen = false; bool isEmaOpen = false; bool isPaOpen = false;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol)
           {
            long magic = PositionGetInteger(POSITION_MAGIC);
            if(magic == InpMagic + 1) 
              {
               isS1Open = true; 
               if(!IsTracked(ticket)) TrackNewTrade(ticket, PositionGetInteger(POSITION_TYPE), TimeCurrent(), currEMA20, currEMA50, currK, currD, currRSI, currTickVol);
              }
            if(magic == InpMagic + 2) isBBOpen = true; 
            if(magic == InpMagic + 3) isEmaOpen = true;
            if(magic == InpMagic + 4) isPaOpen = true;
           }
        }
     }
   
   if(!IsTradingTime()) return;

   // STRATEGY 1: STOCHASTIC TREND MOMENTUM
   if(runStrat1 && !isS1Open)
     {
      bool isTrendBuy = (ema20[1] > ema50[1]);
      bool isTrendSell = (ema50[1] > ema20[1]);
      
      bool isRsiBuyOK = (!InpUseRSI_Filter || currRSI > InpRSI_Center);
      bool isRsiSellOK = (!InpUseRSI_Filter || currRSI < InpRSI_Center);
      
      bool isNearEMA20 = (distPrice_EMA20 <= InpTrend_MaxDist);
      bool isNearEMA50 = (distPrice_EMA50 <= InpTrend_MaxDist_EMA50);
      bool isDistanceOK = (isNearEMA20 || isNearEMA50);
      
      double currentEmaSpread = MathAbs(currEMA20 - currEMA50);
      bool isSpreadOK = (currentEmaSpread >= InpMinEmaSpread_S1);
      
      string stratComment = isNearEMA20 ? "Strategy 1(ema20)" : "Strategy 1(ema50)";
      
      // BUY Logic
      if(isTrendBuy && isDistanceOK && bid > currEMA50 && isRsiBuyOK && isSpreadOK)
        {
         if(currK > InpStoch_Buy_Min && currD > InpStoch_Buy_Min && currK < InpStoch_Buy_Max && currD < InpStoch_Buy_Max && currK > currD && distStoch >= InpStoch_Dist)
           {
            double sl = NormalizeDouble(ask - (InpSL_Trend * point), digits);
            double tp = NormalizeDouble(ask + (InpTP_Trend * point), digits); 
            trade.SetExpertMagicNumber(InpMagic + 1);
            trade.Buy(InpLots, tradeSymbol, ask, sl, tp, stratComment);
           }
        }
      // SELL Logic
      else if(isTrendSell && isDistanceOK && bid < currEMA50 && isRsiSellOK && isSpreadOK)
        {
         if(currK > InpStoch_Sell_Min && currD > InpStoch_Sell_Min && currK < InpStoch_Sell_Max && currD < InpStoch_Sell_Max && currD > currK && distStoch >= InpStoch_Dist)
           {
            double sl = NormalizeDouble(bid + (InpSL_Trend * point), digits);
            double tp = NormalizeDouble(bid - (InpTP_Trend * point), digits);
            trade.SetExpertMagicNumber(InpMagic + 1);
            trade.Sell(InpLots, tradeSymbol, bid, sl, tp, stratComment);
           }
        }
     }

   // STRATEGY 2: BOLLINGER MEAN REVERSION
   if(runStrat2 && !isBBOpen && isNewBar)
     {
      double close1 = closePrices[1]; double lower1 = lowerBand[1]; double upper1 = upperBand[1]; double rsi1 = rsiVal[1];
      if(close1 < lower1 && rsi1 < InpRSI_BuyLvl)
        {
         double sl = NormalizeDouble(ask - (InpSL_BBRule * point), digits);
         double tp = NormalizeDouble(ask + (InpTP_BBRule * point), digits);
         trade.SetExpertMagicNumber(InpMagic + 2);
         trade.Buy(InpLots, tradeSymbol, ask, sl, tp, "BB Reversion");
        }
      else if(close1 > upper1 && rsi1 > InpRSI_SellLvl)
        {
         double sl = NormalizeDouble(bid + (InpSL_BBRule * point), digits);
         double tp = NormalizeDouble(bid - (InpTP_BBRule * point), digits);
         trade.SetExpertMagicNumber(InpMagic + 2);
         trade.Sell(InpLots, tradeSymbol, bid, sl, tp, "BB Reversion");
        }
     }

   // STRATEGY 3: EMA CROSSOVER
   if(runStrat3 && !isEmaOpen && isNewBar)
     {
      double ema20_curr = ema20[1]; double ema50_curr = ema50[1];
      double ema20_prev = ema20[2]; double ema50_prev = ema50[2];
      double currentDist = MathAbs(ema20_curr - ema50_curr);

      if(ema20_prev <= ema50_prev && ema20_curr > ema50_curr && currentDist >= InpMinDist_Strat3)
        {
         trade.SetExpertMagicNumber(InpMagic + 3);
         trade.Buy(InpLots, tradeSymbol, ask, NormalizeDouble(ask - (InpSafetySL_Strat3 * point), digits), 0.0, "EMA Cross");
        }
      if(ema20_prev >= ema50_prev && ema20_curr < ema50_curr && currentDist >= InpMinDist_Strat3)
        {
         trade.SetExpertMagicNumber(InpMagic + 3); 
         trade.Sell(InpLots, tradeSymbol, bid, NormalizeDouble(bid + (InpSafetySL_Strat3 * point), digits), 0.0, "EMA Cross");
        }
     }
     
   // STRATEGY 4: PRICE ACTION
   if(runStrat4 && !isPaOpen && isNewBar)
     {
      bool isTrendUp = (ema20[1] > ema50[1]);
      bool isTrendDown = (ema50[1] > ema20[1]);
      double open1 = openPrices[1]; double close1 = closePrices[1];
      double open2 = openPrices[2]; double close2 = closePrices[2];
      
      if(isTrendUp && close1 > open1 && close2 < open2 && open1 <= close2 && close1 >= open2)
        {
         trade.SetExpertMagicNumber(InpMagic + 4);
         trade.Buy(InpLots, tradeSymbol, ask, NormalizeDouble(ask - (InpSL_Strat4 * point), digits), NormalizeDouble(ask + (InpTP_Strat4 * point), digits), "PA Engulfing");
        }
      if(isTrendDown && close1 < open1 && close2 > open2 && open1 >= close2 && close1 <= open2)
        {
         trade.SetExpertMagicNumber(InpMagic + 4);
         trade.Sell(InpLots, tradeSymbol, bid, NormalizeDouble(bid + (InpSL_Strat4 * point), digits), NormalizeDouble(bid - (InpTP_Strat4 * point), digits), "PA Engulfing");
        }
     }
      
   if(currBarTime != lastBarTime) lastBarTime = currBarTime;
  }
