//+------------------------------------------------------------------+
//|                                     NatGas_Strategy_v12.15.mq5   |
//|                                     Generated by Gemini AI       |
//|      Base: v12.14 (Optimized 80/60 Trailing Stop & Time Filter)  |
//|      Module: Locked Elite Portfolio (S1, S2 Trend, S3 BB Sniper) |
//+------------------------------------------------------------------+
#property copyright "Gemini AI"
#property link      ""
#property version   "12.15"

#include <Trade\Trade.mqh>

//--- Miner Timeframe Enum
enum ENUM_MINER_TF
  {
   TF_M5 = PERIOD_M5,      // 5 Minutes
   TF_M15 = PERIOD_M15,    // 15 Minutes
   TF_H1 = PERIOD_H1,      // 1 Hour
   TF_H4 = PERIOD_H4       // 4 Hours
  };

//--- Input Parameters
input group "=== Strategy Selection ==="
input bool     InpEnableTrading = true;           // Master Toggle: Enable Trading Strategies
input bool     InpRunStrat1     = true;           // Run S1 (Classic Trend)
input bool     InpRunStrat2     = true;           // Run S2 (Trend)
input bool     InpRunStrat3     = true;           // Run S3 (BB Sniper)
input int      InpMagic         = 123456;         // Base Magic Number

input group "=== Lot Size & Limits ==="
input double   InpLots         = 0.12;            // Base Lot Size (High Performance Setting)

input group "=== Global Targets & Risk ==="
input int      InpTakeProfit     = 150;           // Global: Take Profit (Points)
input int      InpStopLoss       = 150;           // Global: Stop Loss (Points)
input bool     InpUseTrailing    = true;          // Global: Enable Trailing Stop
input int      InpTrailing_Start = 80;            // Global: Start trailing after X points profit
input int      InpTrailing_Dist  = 60;            // Global: Trail X points behind price

input group "=== Days to Trade ==="
input bool     InpTradeMonday    = true;          // Trade on Monday
input bool     InpTradeTuesday   = true;          // Trade on Tuesday
input bool     InpTradeWednesday = true;          // Trade on Wednesday
input bool     InpTradeThursday  = true;          // Trade on Thursday
input bool     InpTradeFriday    = true;          // Trade on Friday

input group "=== Time Filter Settings ==="
input bool     InpUseTimeFilter = true;           // Restrict trading to specific hours
input int      InpStartHour     = 8;              // Start Trading (Broker Server Time)
input int      InpEndHour       = 20;             // Stop Trading (Broker Server Time)

input group "=== Friday Gap Protection ==="
input bool     InpUseFridayLogic      = false;    // Enable Friday Anti-Gap Logic (v6.8 Default: FALSE)
input int      InpFridayStopEntryHour = 21;       // Stop New Entries (Hour)
input int      InpFridayCloseAllHour  = 22;       // Close All Positions (Hour)

input group "=== S1 (Classic Trend) Settings ==="
input int      InpTrend_MaxDist_S1 = 5;           // S1: Max allowed distance from EMA20 to enter
input int      InpTrend_MaxDist_EMA50_S1 = 10;    // S1: Max allowed distance from EMA50 to enter
input double   InpMinEmaSpread_S1 = 0.0020;       // S1: MINIMUM EMA SPREAD

// Stoch Settings (S1 M15)
input int      InpStoch_K      = 14;              // S1: Stochastic K Period
input int      InpStoch_D      = 3;               // S1: Stochastic D Period
input int      InpStoch_Slow   = 3;               // S1: Stochastic Slowing
input double   InpStoch_Dist   = 5.0;             // S1: Stochastic Min Spread

input double   InpStoch_Buy_Min  = 20.0;          // S1: Stoch Lower Limit for Buy
input double   InpStoch_Buy_Max  = 80.0;          // S1: Stoch Upper Limit for Buy
input double   InpStoch_Sell_Min = 20.0;          // S1: Stoch Lower Limit for Sell
input double   InpStoch_Sell_Max = 80.0;          // S1: Stoch Upper Limit for Sell

input bool     InpUseRSI_Filter  = true;          // S1: Trade only if RSI agrees with direction
input double   InpRSI_Center     = 50.0;          // S1: Buy > 50, Sell < 50
input int      InpRSI_Period     = 14;            // S1: RSI Period

input group "=== S2 (Trend) Settings ==="
input int      InpPullback_Dist_S2       = 5;     // S2: Max Pullback distance to trigger EMA (Points)

input group "=== S3 (BB Sniper) Settings ==="
input int      InpBands_Period_S3        = 20;    // S3: Bollinger Bands Base Smooth Period
input double   InpBands_Dev_S3           = 2.5;   // S3: Deviation Multiplier (Statistical Ceiling)

input group "=== Shared Indicators ==="
input int      InpEMA9_Period  = 9;               // EMA Fast Period
input int      InpEMA20_Period = 20;              // EMA Fast Period
input int      InpEMA50_Period = 50;              // EMA Slow Period

input group "=== Diagnostics & Logging ==="
input bool     InpLogAllCandles = false;          // Record "NO TRADE" candles to CSV

input group "=== M5 Pattern Data Miner ==="
input bool     InpRunM5DataMiner = false;         // Toggle M5 Event Data Miner
input bool     InpLogOnlyEvents  = false;         // FALSE = Continuous Momentum Tracking

//--- Global Variables
CTrade         trade;
int            handle_EMA20;     // S1 & S3 Fast Line
int            handle_EMA50;     // S1 & S3 Slow Line reference
int            handle_Stoch;
int            handle_RSI;
int            handle_Bands_M15; // S3 Volatility Envelope Engine
string         tradeSymbol;
datetime       lastBarTime = 0;
string         csvFilename_S1_Audit = "";
string         csvFilename_S2_Audit = "";
string         csvFilename_S3_Audit = "";

//--- M5 Pattern Data Miner & Strategy 2 Variables
int            handle_EMA9_M5;   // S1 MTF Momentum Filter
int            handle_EMA20_M5;
int            handle_EMA50_M5;
int            handle_Stoch_M5;
int            handle_RSI_M5;
datetime       lastBarTime_M5 = 0;
datetime       lastBarTime_M5_Trade = 0;
string         csvFilename_M5_Miner = "";

//--- Statistics Variables
int    stat_S1_Total = 0; int stat_S1_Wins = 0; int stat_S1_Loss = 0; double stat_S1_PL = 0.0; double stat_S1_WinPL = 0.0; double stat_S1_LossPL = 0.0;
int    stat_S2_Total = 0; int stat_S2_Wins = 0; int stat_S2_Loss = 0; double stat_S2_PL = 0.0; double stat_S2_WinPL = 0.0; double stat_S2_LossPL = 0.0;
int    stat_S3_Total = 0; int stat_S3_Wins = 0; int stat_S3_Loss = 0; double stat_S3_PL = 0.0; double stat_S3_WinPL = 0.0; double stat_S3_LossPL = 0.0;

//--- Trade Memory Struct for Synchronous Diagnostics 
struct TradeMemory
  {
   ulong    ticket;
   long     magic;     
   long     type;
   datetime entryTime;
   double   ind1;      // Strategy Parameter Trace 1
   double   ind2;      // Strategy Parameter Trace 2
   double   ind3;      // Strategy Parameter Trace 3
   double   stochK;
   double   stochD;
   double   rsi;
   long     tickVol;
   double   sl_level;
   bool     active;
  };
TradeMemory activeTrades[];

//+------------------------------------------------------------------+
//| Helper: Format Double for European Excel (Replaces . with ,)     |
//+------------------------------------------------------------------+
string D2S(double value, int digits)
  {
   string str = DoubleToString(value, digits);
   StringReplace(str, ".", ","); // Convert decimal point to comma for Excel
   return str;
  }

//+------------------------------------------------------------------+
//| Helper: Get Day String                                           |
//+------------------------------------------------------------------+
string GetDayStr(int day_of_week)
  {
   switch(day_of_week)
     {
      case 0: return "Sunday";
      case 1: return "Monday";
      case 2: return "Tuesday";
      case 3: return "Wednesday";
      case 4: return "Thursday";
      case 5: return "Friday";
      case 6: return "Saturday";
     }
   return "Unknown";
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   tradeSymbol = _Symbol;
   
   Print(">>> EA INITIALIZING (v12.15) on chart: ", tradeSymbol);
   long hwid = AccountInfoInteger(ACCOUNT_LOGIN);
   ulong msCount = GetMicrosecondCount(); 
   
   // --- CORE INDICATORS & HANDLES (M15) ---
   handle_EMA20 = iMA(tradeSymbol, PERIOD_M15, InpEMA20_Period, 0, MODE_EMA, PRICE_CLOSE);
   handle_EMA50 = iMA(tradeSymbol, PERIOD_M15, InpEMA50_Period, 0, MODE_EMA, PRICE_CLOSE);
   handle_Stoch = iStochastic(tradeSymbol, PERIOD_M15, InpStoch_K, InpStoch_D, InpStoch_Slow, MODE_SMA, STO_LOWHIGH);
   handle_RSI   = iRSI(tradeSymbol, PERIOD_M15, InpRSI_Period, PRICE_CLOSE);
   handle_Bands_M15 = iBands(tradeSymbol, PERIOD_M15, InpBands_Period_S3, 0, InpBands_Dev_S3, PRICE_CLOSE);
   
   // --- CORE INDICATORS & HANDLES (M5) ---
   handle_EMA9_M5  = iMA(tradeSymbol, PERIOD_M5, InpEMA9_Period, 0, MODE_EMA, PRICE_CLOSE);
   handle_EMA20_M5 = iMA(tradeSymbol, PERIOD_M5, InpEMA20_Period, 0, MODE_EMA, PRICE_CLOSE);
   handle_EMA50_M5 = iMA(tradeSymbol, PERIOD_M5, InpEMA50_Period, 0, MODE_EMA, PRICE_CLOSE);
   handle_Stoch_M5 = iStochastic(tradeSymbol, PERIOD_M5, InpStoch_K, InpStoch_D, InpStoch_Slow, MODE_SMA, STO_LOWHIGH);
   handle_RSI_M5   = iRSI(tradeSymbol, PERIOD_M5, InpRSI_Period, PRICE_CLOSE);

   if(handle_EMA20 == INVALID_HANDLE || handle_EMA50 == INVALID_HANDLE || 
      handle_Stoch == INVALID_HANDLE || handle_RSI == INVALID_HANDLE || handle_Bands_M15 == INVALID_HANDLE ||
      handle_EMA9_M5 == INVALID_HANDLE || handle_EMA20_M5 == INVALID_HANDLE || handle_EMA50_M5 == INVALID_HANDLE || handle_Stoch_M5 == INVALID_HANDLE)
     {
      Print("Error creating indicator handles.");
      return(INIT_FAILED);
     }

   // --- STRATEGY AUDIT CSV INITIALIZATION ---
   if(InpEnableTrading)
     {
      // S1 Audit Init
      csvFilename_S1_Audit = "Strategy1_Audit_v12.15_" + IntegerToString(hwid) + ".csv";
      int file1 = FileOpen(csvFilename_S1_Audit, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file1 != INVALID_HANDLE) {
         FileWrite(file1, "Ticket", "Magic", "Strategy", "Type", "Result", "Exit_Reason", "Profit_Loss", "EntryDate", "ExitDate", "EntryDay", "ExitDay", "EntryTime", "ExitTime", "EMA_Fast", "EMA_Mid", "EMA_Slow", "StochK", "StochD", "RSI", "TickVol");
         FileClose(file1);
      }
      
      // S2 Audit Init
      csvFilename_S2_Audit = "Strategy2_Audit_v12.15_" + IntegerToString(hwid) + ".csv";
      int file2 = FileOpen(csvFilename_S2_Audit, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file2 != INVALID_HANDLE) {
         FileWrite(file2, "Ticket", "Magic", "Strategy", "Type", "Result", "Exit_Reason", "Profit_Loss", "EntryDate", "ExitDate", "EntryDay", "ExitDay", "EntryTime", "ExitTime", "M5_EMA9", "M5_EMA20", "StochK", "StochD", "RSI", "TickVol");
         FileClose(file2);
      }

      // S3 Audit Init
      csvFilename_S3_Audit = "Strategy3_Audit_v12.15_" + IntegerToString(hwid) + ".csv";
      int file3 = FileOpen(csvFilename_S3_Audit, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file3 != INVALID_HANDLE) {
         FileWrite(file3, "Ticket", "Magic", "Strategy", "Type", "Result", "Exit_Reason", "Profit_Loss", "EntryDate", "ExitDate", "EntryDay", "ExitDay", "EntryTime", "ExitTime", "EMA20", "EMA50", "BB_Upper", "BB_Lower", "Unused_Col", "RSI_M15", "TickVol");
         FileClose(file3);
      }
     }

   // --- M5 PATTERN DATA MINER INITIALIZATION ---
   if(InpRunM5DataMiner)
     {
      csvFilename_M5_Miner = "M5_Pattern_Miner_" + IntegerToString(hwid) + "_" + IntegerToString(msCount) + ".csv";
      int fileM5 = FileOpen(csvFilename_M5_Miner, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(fileM5 != INVALID_HANDLE)
        {
         FileWrite(fileM5, "Date", "Time", "Open", "High", "Low", "Close", "Candle_Points", "Points_Dir", "Cumulative_Points", "EMA_Cross", "EMA20", "EMA50", "Stoch_Cross", "Stoch_K", "Stoch_D", "RSI_Cross", "RSI_Val", "Event_Price");
         FileClose(fileM5);
        }
     }

   trade.SetExpertMagicNumber(InpMagic);
   trade.LogLevel(LOG_LEVEL_NO); 
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   PrintFormat("S1 (Classic Trend): win=%d (%.2f), loss=%d (%.2f) | S2 (Trend): win=%d (%.2f), loss=%d (%.2f) | S3 (BB Sniper): win=%d (%.2f), loss=%d (%.2f) | Total: win=%d (%.2f), loss=%d (%.2f) | Net PL: %.2f", 
               stat_S1_Wins, stat_S1_WinPL, stat_S1_Loss, stat_S1_LossPL,
               stat_S2_Wins, stat_S2_WinPL, stat_S2_Loss, stat_S2_LossPL,
               stat_S3_Wins, stat_S3_WinPL, stat_S3_Loss, stat_S3_LossPL,
               (stat_S1_Wins + stat_S2_Wins + stat_S3_Wins), 
               (stat_S1_WinPL + stat_S2_WinPL + stat_S3_WinPL),
               (stat_S1_Loss + stat_S2_Loss + stat_S3_Loss), 
               (stat_S1_LossPL + stat_S2_LossPL + stat_S3_LossPL),
               (stat_S1_PL + stat_S2_PL + stat_S3_PL));
   
   if(handle_EMA20 != INVALID_HANDLE) IndicatorRelease(handle_EMA20); 
   if(handle_EMA50 != INVALID_HANDLE) IndicatorRelease(handle_EMA50); 
   if(handle_Stoch != INVALID_HANDLE) IndicatorRelease(handle_Stoch); 
   if(handle_RSI != INVALID_HANDLE) IndicatorRelease(handle_RSI);
   if(handle_Bands_M15 != INVALID_HANDLE) IndicatorRelease(handle_Bands_M15);
   if(handle_EMA9_M5 != INVALID_HANDLE) IndicatorRelease(handle_EMA9_M5); 
   if(handle_EMA20_M5 != INVALID_HANDLE) IndicatorRelease(handle_EMA20_M5); 
   if(handle_EMA50_M5 != INVALID_HANDLE) IndicatorRelease(handle_EMA50_M5);
   if(handle_Stoch_M5 != INVALID_HANDLE) IndicatorRelease(handle_Stoch_M5); 
   if(handle_RSI_M5 != INVALID_HANDLE) IndicatorRelease(handle_RSI_M5);

   Comment("");
  }

//+------------------------------------------------------------------+
//| Helper: M5 Pattern Data Miner Execution Logic                    |
//+------------------------------------------------------------------+
void RunM5PatternMiner()
  {
   if(!InpRunM5DataMiner) return;

   datetime currM5Time = iTime(tradeSymbol, PERIOD_M5, 0);
   if(currM5Time == 0) return; 
   
   if(lastBarTime_M5 == 0)
     {
      lastBarTime_M5 = currM5Time;
      return;
     }
     
   if(currM5Time != lastBarTime_M5)
     {
      static long cumulativePoints = 0; 
      
      datetime closedBarTime = iTime(tradeSymbol, PERIOD_M5, 1);
      
      double open[], high[], low[], close[];
      double ema20[], ema50[], stochK[], stochD[], rsi[];
      
      ArraySetAsSeries(open, true); ArraySetAsSeries(high, true);
      ArraySetAsSeries(low, true); ArraySetAsSeries(close, true);
      ArraySetAsSeries(ema20, true); ArraySetAsSeries(ema50, true);
      ArraySetAsSeries(stochK, true); ArraySetAsSeries(stochD, true); ArraySetAsSeries(rsi, true);
      
      if(CopyOpen(tradeSymbol, PERIOD_M5, 1, 3, open) != 3) return;
      if(CopyHigh(tradeSymbol, PERIOD_M5, 1, 3, high) != 3) return;
      if(CopyLow(tradeSymbol, PERIOD_M5, 1, 3, low) != 3) return;
      if(CopyClose(tradeSymbol, PERIOD_M5, 1, 3, close) != 3) return;
      
      if(CopyBuffer(handle_EMA20_M5, 0, 0, 3, ema20) != 3) return;
      if(CopyBuffer(handle_EMA50_M5, 0, 0, 3, ema50) != 3) return;
      if(CopyBuffer(handle_Stoch_M5, 0, 0, 3, stochK) != 3) return;
      if(CopyBuffer(handle_Stoch_M5, 1, 0, 3, stochD) != 3) return;
      if(CopyBuffer(handle_RSI_M5, 0, 0, 3, rsi) != 3) return;

      // 1. Check EMA Cross
      string emaEvent = "None";
      if(ema20[2] <= ema50[2] && ema20[1] > ema50[1]) emaEvent = "Bullish_Cross";
      if(ema20[2] >= ema50[2] && ema20[1] < ema50[1]) emaEvent = "Bearish_Cross";

      // 2. Check Stochastic Cross
      string stochEvent = "None";
      if(stochK[2] <= 20 && stochK[2] <= stochD[2] && stochK[1] > stochD[1]) stochEvent = "OS_Buy_Cross";
      if(stochK[2] >= 80 && stochK[2] >= stochD[2] && stochK[1] < stochD[1]) stochEvent = "OB_Sell_Cross";

      // 3. Check RSI Cross 50
      string rsiEvent = "None";
      if(rsi[2] <= 50 && rsi[1] > 50) rsiEvent = "Crossed_Above_50";
      if(rsi[2] >= 50 && rsi[1] < 50) rsiEvent = "Crossed_Below_50";

      bool hasEvent = (emaEvent != "None" || stochEvent != "None" || rsiEvent != "None");

      if(!InpLogOnlyEvents || hasEvent)
        {
         double point_val = SymbolInfoDouble(tradeSymbol, SYMBOL_POINT);
         long candlePoints = (long)MathRound((high[0] - low[0]) / point_val); 
         long dirPoints = (close[0] >= open[0]) ? candlePoints : -candlePoints;
         cumulativePoints += dirPoints;
         
         string pointsDirStr = (dirPoints >= 0) ? "+" + IntegerToString(dirPoints) : IntegerToString(dirPoints);
         
         MqlDateTime tm;
         TimeToStruct(closedBarTime, tm);
         string dateStr = TimeToString(closedBarTime, TIME_DATE); StringReplace(dateStr, ".", "/");
         string timeStr = TimeToString(closedBarTime, TIME_MINUTES); StringReplace(timeStr, ":", ".");
         
         string eventPrice = (hasEvent) ? D2S(close[0], 4) : "";
         
         int file = FileOpen(csvFilename_M5_Miner, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
         if(file != INVALID_HANDLE)
           {
            FileSeek(file, 0, SEEK_END);
            FileWrite(file, dateStr, timeStr, D2S(open[0], 4), D2S(high[0], 4), D2S(low[0], 4), D2S(close[0], 4), 
                      IntegerToString(candlePoints), pointsDirStr, IntegerToString(cumulativePoints), 
                      emaEvent, D2S(ema20[1], 4), D2S(ema50[1], 4), stochEvent, D2S(stochK[1], 2), D2S(stochD[1], 2), rsiEvent, D2S(rsi[1], 2), eventPrice);
            FileClose(file);
           }
        }
        
      lastBarTime_M5 = currM5Time;
     }
  }

//+------------------------------------------------------------------+
//| Helper: Check Trading Time & Days                                |
//+------------------------------------------------------------------+
bool IsTradingTime()
  {
   datetime currentTime = TimeCurrent();
   MqlDateTime tm;
   TimeToStruct(currentTime, tm);
   
   if(tm.day_of_week == 1 && !InpTradeMonday) return(false);
   if(tm.day_of_week == 2 && !InpTradeTuesday) return(false);
   if(tm.day_of_week == 3 && !InpTradeWednesday) return(false);
   if(tm.day_of_week == 4 && !InpTradeThursday) return(false);
   if(tm.day_of_week == 5 && !InpTradeFriday) return(false);
   
   if(InpUseFridayLogic && tm.day_of_week == 5 && tm.hour >= InpFridayStopEntryHour) return(false);
     
   if(!InpUseTimeFilter) return(true);
   if(tm.hour >= InpStartHour && tm.hour < InpEndHour) return(true);
   
   return(false);
  }

//+------------------------------------------------------------------+
//| Helper: Friday Anti-Gap Protection                               |
//+------------------------------------------------------------------+
void CheckFridayClose()
  {
   if(!InpUseFridayLogic) return;
   
   MqlDateTime tm;
   TimeToStruct(TimeCurrent(), tm);
   
   if(tm.day_of_week == 5 && tm.hour >= InpFridayCloseAllHour)
     {
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i);
         if(PositionSelectByTicket(ticket))
           {
            if(PositionGetString(POSITION_SYMBOL) == tradeSymbol) trade.PositionClose(ticket);
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Helper: Synchronous Diagnostic CSV Logger (w/ Exit Reasons)      |
//+------------------------------------------------------------------+
bool IsTracked(ulong ticket)
  {
   for(int i = 0; i < ArraySize(activeTrades); i++)
     {
      if(activeTrades[i].active && activeTrades[i].ticket == ticket) return true;
     }
   return false;
  }

void TrackNewTrade(ulong ticket, long magic, long type, datetime entryTime, double ind1, double ind2, double ind3, double stochK, double stochD, double rsi, long tickVol, double sl_level)
  {
   int size = ArraySize(activeTrades);
   for(int i = 0; i < size; i++)
     {
      if(!activeTrades[i].active)
        {
         activeTrades[i].ticket = ticket;
         activeTrades[i].magic = magic;
         activeTrades[i].type = type;
         activeTrades[i].entryTime = entryTime;
         activeTrades[i].ind1 = ind1; activeTrades[i].ind2 = ind2; activeTrades[i].ind3 = ind3; 
         activeTrades[i].stochK = stochK; activeTrades[i].stochD = stochD; 
         activeTrades[i].rsi = rsi; activeTrades[i].tickVol = tickVol;
         activeTrades[i].sl_level = sl_level;
         activeTrades[i].active = true;
         return;
        }
     }
   ArrayResize(activeTrades, size + 1);
   activeTrades[size].ticket = ticket; 
   activeTrades[size].magic = magic;
   activeTrades[size].type = type; 
   activeTrades[size].entryTime = entryTime;
   activeTrades[size].ind1 = ind1; activeTrades[size].ind2 = ind2; activeTrades[size].ind3 = ind3; 
   activeTrades[size].stochK = stochK; activeTrades[size].stochD = stochD; 
   activeTrades[size].rsi = rsi; activeTrades[size].tickVol = tickVol;
   activeTrades[size].sl_level = sl_level;
   activeTrades[size].active = true;
  }

void UpdateTradeSL(ulong ticket, double newSL)
  {
   for(int i = 0; i < ArraySize(activeTrades); i++)
     {
      if(activeTrades[i].active && activeTrades[i].ticket == ticket)
        {
         activeTrades[i].sl_level = newSL;
         break;
        }
     }
  }

bool ProcessClosedTrade(TradeMemory &mem)
  {
   HistorySelect(0, TimeCurrent());
   double profit = 0;
   datetime exitTime = 0; bool found = false;
   string exitReason = "Unknown";

   int total = HistoryDealsTotal();
   for(int i = total - 1; i >= 0; i--)
     {
      ulong dealTicket = HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(dealTicket, DEAL_POSITION_ID) == mem.ticket)
        {
         if(HistoryDealGetInteger(dealTicket, DEAL_ENTRY) == DEAL_ENTRY_OUT)
           {
            profit += HistoryDealGetDouble(dealTicket, DEAL_PROFIT) + HistoryDealGetDouble(dealTicket, DEAL_SWAP) + HistoryDealGetDouble(dealTicket, DEAL_COMMISSION);
            exitTime = (datetime)HistoryDealGetInteger(dealTicket, DEAL_TIME);
            
            long reasonCode = HistoryDealGetInteger(dealTicket, DEAL_REASON);
            if(reasonCode == DEAL_REASON_SL)
              {
               // FIX: Slippage buffer reporting correctly.
               if(profit > 0) exitReason = "Trailing Stop";
               else exitReason = "Stop Loss";
              }
            else if(reasonCode == DEAL_REASON_TP) exitReason = "Take Profit";
            else if(reasonCode == DEAL_REASON_CLIENT)
              {
               MqlDateTime tm; TimeToStruct(exitTime, tm);
               if(InpUseFridayLogic && tm.day_of_week == 5 && tm.hour >= InpFridayCloseAllHour) exitReason = "Friday Close";
               else exitReason = "Manual/Logic Close";
              }
            
            found = true; break;
           }
        }
     }

   if(!found) return false;
   string resultStr = (profit > 0) ? "Win" : "Loss";
   string typeStr = (mem.type == POSITION_TYPE_BUY) ? "Buy" : "Sell";
   string stratStr = "Unknown";
   
   string targetAuditFile = "";
   if(mem.magic == InpMagic + 1)
     {
      stratStr = "S1"; stat_S1_Total++;
      if(profit > 0) { stat_S1_Wins++; stat_S1_WinPL += profit; } else { stat_S1_Loss++; stat_S1_LossPL += profit; }
      stat_S1_PL += profit; targetAuditFile = csvFilename_S1_Audit;
     }
   else if(mem.magic == InpMagic + 2)
     {
      stratStr = "S2"; stat_S2_Total++;
      if(profit > 0) { stat_S2_Wins++; stat_S2_WinPL += profit; } else { stat_S2_Loss++; stat_S2_LossPL += profit; }
      stat_S2_PL += profit; targetAuditFile = csvFilename_S2_Audit;
     }
   else if(mem.magic == InpMagic + 3)
     {
      stratStr = "S3"; stat_S3_Total++;
      if(profit > 0) { stat_S3_Wins++; stat_S3_WinPL += profit; } else { stat_S3_Loss++; stat_S3_LossPL += profit; }
      stat_S3_PL += profit; targetAuditFile = csvFilename_S3_Audit;
     }
   
   MqlDateTime inTm; TimeToStruct(mem.entryTime, inTm); string inDay = GetDayStr(inTm.day_of_week);
   string inDate = TimeToString(mem.entryTime, TIME_DATE); StringReplace(inDate, ".", "/");
   string inTime = TimeToString(mem.entryTime, TIME_MINUTES); StringReplace(inTime, ":", ".");

   MqlDateTime outTm; TimeToStruct(exitTime, outTm);
   string outDay = GetDayStr(outTm.day_of_week);
   string outDate = TimeToString(exitTime, TIME_DATE); StringReplace(outDate, ".", "/");
   string outTime = TimeToString(exitTime, TIME_MINUTES); StringReplace(outTime, ":", ".");
   
   if(targetAuditFile != "")
     {
      string ind1_str = D2S(mem.ind1, 4);
      string ind2_str = D2S(mem.ind2, 4);
      string ind3_str = D2S(mem.ind3, 4);
      string k_str = (mem.magic == InpMagic + 3) ? D2S(mem.stochK, 4) : D2S(mem.stochK, 2); 
      string d_str = D2S(mem.stochD, 2);
      string rsi_str = D2S(mem.rsi, 2);
      
      int file = FileOpen(targetAuditFile, FILE_CSV|FILE_WRITE|FILE_READ|FILE_COMMON|FILE_ANSI, ';');
      if(file != INVALID_HANDLE)
        {
         FileSeek(file, 0, SEEK_END);
         FileWrite(file, IntegerToString(mem.ticket), IntegerToString(mem.magic), stratStr, typeStr, resultStr, exitReason, D2S(profit, 2), 
                   inDate, outDate, inDay, outDay, inTime, outTime,
                   ind1_str, ind2_str, ind3_str, k_str, d_str, rsi_str, IntegerToString(mem.tickVol));
         FileClose(file);
        }
     }
   return true;
  }

//+------------------------------------------------------------------+
//| Helper: Consolidated Trailing Stops for All Strategies           |
//+------------------------------------------------------------------+
void CheckTrailingStops(double point, int digits)
{
   if(!InpUseTrailing) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionSelectByTicket(PositionGetTicket(i)))
      {
         long magic = PositionGetInteger(POSITION_MAGIC);
         
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol && (magic == InpMagic + 1 || magic == InpMagic + 2 || magic == InpMagic + 3))
         {
            ulong ticket = PositionGetInteger(POSITION_TICKET);
            long type = PositionGetInteger(POSITION_TYPE);
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentTP = PositionGetDouble(POSITION_TP);
            
            if(type == POSITION_TYPE_BUY)
            {
               double bid = SymbolInfoDouble(tradeSymbol, SYMBOL_BID);
               if((bid - openPrice) >= InpTrailing_Start * point)
               {
                  double newSL = NormalizeDouble(bid - (InpTrailing_Dist * point), digits);
                  // Silent 30-point internal step to prevent log spam
                  if(currentSL == 0.0 || newSL >= currentSL + (30 * point)) 
                    {
                     trade.PositionModify(ticket, newSL, currentTP);
                     UpdateTradeSL(ticket, newSL);
                    }
               }
            }
            else if(type == POSITION_TYPE_SELL)
            {
               double ask = SymbolInfoDouble(tradeSymbol, SYMBOL_ASK);
               if((openPrice - ask) >= InpTrailing_Start * point)
               {
                  double newSL = NormalizeDouble(ask + (InpTrailing_Dist * point), digits);
                  // Silent 30-point internal step to prevent log spam
                  if(currentSL == 0.0 || newSL <= currentSL - (30 * point)) 
                    {
                     trade.PositionModify(ticket, newSL, currentTP);
                     UpdateTradeSL(ticket, newSL);
                    }
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // --- 0. Trigger M5 Data Miner ---
   RunM5PatternMiner();
   if(!InpEnableTrading) return; 
   
   // --- 1. Friday Anti-Gap Protection ---
   CheckFridayClose();
   
   // --- 2. Get Core Indicator Data (M15 & M5) ---
   double ema20[], ema50[], stochK[], stochD[], rsiVal[], upperBB[], lowerBB[], midBB[];
   double openM15[], highM15[], lowM15[], closeM15[];
   long tickVol[];
   
   ArraySetAsSeries(ema20, true); ArraySetAsSeries(ema50, true); 
   ArraySetAsSeries(stochK, true); ArraySetAsSeries(stochD, true); ArraySetAsSeries(rsiVal, true);
   ArraySetAsSeries(upperBB, true); ArraySetAsSeries(lowerBB, true); ArraySetAsSeries(midBB, true);
   ArraySetAsSeries(openM15, true); ArraySetAsSeries(highM15, true); ArraySetAsSeries(lowM15, true); ArraySetAsSeries(closeM15, true);
   ArraySetAsSeries(tickVol, true);

   if(CopyBuffer(handle_EMA20, 0, 0, 4, ema20) != 4) return;
   if(CopyBuffer(handle_EMA50, 0, 0, 4, ema50) != 4) return;
   if(CopyBuffer(handle_Stoch, 0, 0, 4, stochK) != 4) return;
   if(CopyBuffer(handle_Stoch, 1, 0, 4, stochD) != 4) return; 
   if(CopyBuffer(handle_RSI, 0, 0, 2, rsiVal) != 2) return;
   if(CopyBuffer(handle_Bands_M15, 0, 0, 3, midBB) != 3) return;   
   if(CopyBuffer(handle_Bands_M15, 1, 0, 3, upperBB) != 3) return; 
   if(CopyBuffer(handle_Bands_M15, 2, 0, 3, lowerBB) != 3) return; 
   if(CopyOpen(tradeSymbol, PERIOD_M15, 0, 3, openM15) != 3) return;
   if(CopyHigh(tradeSymbol, PERIOD_M15, 0, 3, highM15) != 3) return;
   if(CopyLow(tradeSymbol, PERIOD_M15, 0, 3, lowM15) != 3) return;
   if(CopyClose(tradeSymbol, PERIOD_M15, 0, 3, closeM15) != 3) return;
   if(CopyTickVolume(tradeSymbol, PERIOD_M15, 0, 2, tickVol) != 2) return;
   
   // --- Fetch Global MTF M5 Momentum data ---
   double m5_e9[], m5_e20[];
   ArraySetAsSeries(m5_e9, true);
   ArraySetAsSeries(m5_e20, true);
   if(CopyBuffer(handle_EMA9_M5, 0, 0, 3, m5_e9) != 3) return;
   if(CopyBuffer(handle_EMA20_M5, 0, 0, 3, m5_e20) != 3) return;

   double bid = SymbolInfoDouble(tradeSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(tradeSymbol, SYMBOL_ASK);
   double point = SymbolInfoDouble(tradeSymbol, SYMBOL_POINT);
   int digits = (int)SymbolInfoInteger(tradeSymbol, SYMBOL_DIGITS);

   double currEMA20 = ema20[0]; double currEMA50 = ema50[0]; 
   double currK = stochK[0];    double currD = stochD[0];
   double currRSI = rsiVal[0];
   long currTickVol = tickVol[0];
   
   double distStoch = MathAbs(currK - currD);
   double distPrice_EMA20_S1 = MathAbs(bid - currEMA20) / point; 
   double distPrice_EMA50_S1 = MathAbs(bid - currEMA50) / point; 
   
   // --- SYNCHRONOUS DIAGNOSTIC TRACKER (Exit Check) ---
   for(int i = 0; i < ArraySize(activeTrades); i++)
     {
      if(activeTrades[i].active)
        {
         if(!PositionSelectByTicket(activeTrades[i].ticket))
           {
            if(ProcessClosedTrade(activeTrades[i])) activeTrades[i].active = false;
           }
        }
     }

   datetime currBarTime = iTime(tradeSymbol, PERIOD_M15, 0);
   bool isNewBar = (currBarTime != lastBarTime);
   
   static datetime lastBarTime_M1 = 0;
   datetime currBarTime_M1 = iTime(tradeSymbol, PERIOD_M1, 0);
   bool isNewBar_M1 = (currBarTime_M1 != lastBarTime_M1);
   if(isNewBar_M1) lastBarTime_M1 = currBarTime_M1;
     
   // --- TRAILING STOP MANAGEMENT ---
   // Evaluates the trail once per minute. This perfectly stops MT5 journal spam natively.
   if(isNewBar_M1)
     {
      CheckTrailingStops(point, digits);
     }

   bool runStrat1 = InpRunStrat1;
   bool runStrat2 = InpRunStrat2;
   bool runStrat3 = InpRunStrat3;
   
   bool isS1Open = false; bool isS2Open = false; bool isS3Open = false; 

   // Check Active Positions
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == tradeSymbol)
           {
            long magic = PositionGetInteger(POSITION_MAGIC);
            
            if(magic == InpMagic + 1) 
              {
               isS1Open = true;
               if(!IsTracked(ticket)) TrackNewTrade(ticket, magic, PositionGetInteger(POSITION_TYPE), TimeCurrent(), currEMA20, currEMA50, 0.0, currK, currD, currRSI, currTickVol, PositionGetDouble(POSITION_SL));
              }
            else if(magic == InpMagic + 2) 
              {
               isS2Open = true;
               if(!IsTracked(ticket)) TrackNewTrade(ticket, magic, PositionGetInteger(POSITION_TYPE), TimeCurrent(), m5_e9[0], m5_e20[0], 0.0, currK, currD, currRSI, currTickVol, PositionGetDouble(POSITION_SL));
              }
            else if(magic == InpMagic + 3)
              {
               isS3Open = true;
               if(!IsTracked(ticket)) TrackNewTrade(ticket, magic, PositionGetInteger(POSITION_TYPE), TimeCurrent(), currEMA20, currEMA50, upperBB[1], lowerBB[1], 0.0, currRSI, currTickVol, PositionGetDouble(POSITION_SL));
              }
           }
        }
     }
   
   if(!IsTradingTime()) return;

   bool isM5MomUp = (m5_e9[1] > m5_e20[1]);
   bool isM5MomDown = (m5_e9[1] < m5_e20[1]);

   // =========================================================================================
   // STRATEGY 1: STOCHASTIC TREND MOMENTUM (Classic v6.8 + M5 MTF Filter)
   // =========================================================================================
   if(runStrat1 && !isS1Open)
     {
      bool isTrendBuy = (ema20[1] > ema50[1]);
      bool isTrendSell = (ema50[1] > ema20[1]);
      
      bool isRsiBuyOK = (!InpUseRSI_Filter || currRSI > InpRSI_Center);
      bool isRsiSellOK = (!InpUseRSI_Filter || currRSI < InpRSI_Center);
      
      bool isNearEMA20 = (distPrice_EMA20_S1 <= InpTrend_MaxDist_S1);
      bool isNearEMA50 = (distPrice_EMA50_S1 <= InpTrend_MaxDist_EMA50_S1);
      bool isDistanceOK = (isNearEMA20 || isNearEMA50);
      
      double currentEmaSpread = MathAbs(currEMA20 - currEMA50);
      bool isSpreadOK = (currentEmaSpread >= InpMinEmaSpread_S1);
      
      string stratCommentBuy = isNearEMA20 ? "S1 Buy(ema20)" : "S1 Buy(ema50)";
      string stratCommentSell = isNearEMA20 ? "S1 Sell(ema20)" : "S1 Sell(ema50)";
      
      if(isTrendBuy && isDistanceOK && bid > currEMA50 && isRsiBuyOK && isSpreadOK && isM5MomUp)
        {
         if(currK > InpStoch_Buy_Min && currD > InpStoch_Buy_Min && currK < InpStoch_Buy_Max && currD < InpStoch_Buy_Max && currK > currD && distStoch >= InpStoch_Dist)
           {
            double sl = NormalizeDouble(ask - (InpStopLoss * point), digits);
            double tp = NormalizeDouble(ask + (InpTakeProfit * point), digits); 
            trade.SetExpertMagicNumber(InpMagic + 1);
            if(trade.Buy(InpLots, tradeSymbol, ask, sl, tp, stratCommentBuy))
              {
               PrintFormat("📈 [OPEN S1 BUY] Price: %.3f | EMA20: %.3f | EMA50: %.3f | Gap: %.1f | S_K(M15): %.1f | S_D(M15): %.1f | RSI: %.1f", 
                           ask, currEMA20, currEMA50, currentEmaSpread / point, currK, currD, currRSI);
               isS1Open = true; 
              }
           }
        }
      else if(isTrendSell && isDistanceOK && bid < currEMA50 && isRsiSellOK && isSpreadOK && isM5MomDown)
        {
         if(currK > InpStoch_Sell_Min && currD > InpStoch_Sell_Min && currK < InpStoch_Sell_Max && currD < InpStoch_Sell_Max && currD > currK && distStoch >= InpStoch_Dist)
           {
            double sl = NormalizeDouble(bid + (InpStopLoss * point), digits);
            double tp = NormalizeDouble(bid - (InpTakeProfit * point), digits);
            trade.SetExpertMagicNumber(InpMagic + 1);
            if(trade.Sell(InpLots, tradeSymbol, bid, sl, tp, stratCommentSell))
              {
               PrintFormat("📉 [OPEN S1 SELL] Price: %.3f | EMA20: %.3f | EMA50: %.3f | Gap: %.1f | S_K(M15): %.1f | S_D(M15): %.1f | RSI: %.1f", 
                           bid, currEMA20, currEMA50, currentEmaSpread / point, currK, currD, currRSI);
               isS1Open = true;
              }
           }
        }
     }

   // =========================================================================================
   // STRATEGY 2: MTF STOCHASTIC & EMA SYNERGY (Trend Continuation)
   // =========================================================================================
   if(runStrat2 && !isS2Open)
     {
      // Strong M15 macro momentum confirming direction
      bool isS2_StochBuy = (currK > 50 && currK > currD); 
      bool isS2_StochSell = (currK < 50 && currK < currD);
      
      // The Deep Dip Execution (Price breaks through EMA 9 and stabs EMA 20)
      bool isDipBuy = (ask < m5_e9[0] && (MathAbs(ask - m5_e20[0]) / point) <= InpPullback_Dist_S2);
      bool isRallySell = (bid > m5_e9[0] && (MathAbs(bid - m5_e20[0]) / point) <= InpPullback_Dist_S2);
      
      if(isS2_StochBuy && isM5MomUp && isDipBuy)
        {
         double sl = NormalizeDouble(ask - (InpStopLoss * point), digits);
         double tp = NormalizeDouble(ask + (InpTakeProfit * point), digits); 
         trade.SetExpertMagicNumber(InpMagic + 2);
         if(trade.Buy(InpLots, tradeSymbol, ask, sl, tp, "S2 Trend Buy"))
           {
            PrintFormat("📈 [OPEN S2 BUY] Price: %.3f | M15_K: %.1f | M15_D: %.1f | M5_EMA9: %.3f | M5_EMA20: %.3f", 
                        ask, currK, currD, m5_e9[0], m5_e20[0]);
            isS2Open = true; 
           }
        }
      else if(isS2_StochSell && isM5MomDown && isRallySell)
        {
         double sl = NormalizeDouble(bid + (InpStopLoss * point), digits);
         double tp = NormalizeDouble(bid - (InpTakeProfit * point), digits);
         trade.SetExpertMagicNumber(InpMagic + 2);
         if(trade.Sell(InpLots, tradeSymbol, bid, sl, tp, "S2 Trend Sell"))
           {
            PrintFormat("📉 [OPEN S2 SELL] Price: %.3f | M15_K: %.1f | M15_D: %.1f | M5_EMA9: %.3f | M5_EMA20: %.3f", 
                        bid, currK, currD, m5_e9[0], m5_e20[0]);
            isS2Open = true;
           }
        }
     }

   // =========================================================================================
   // STRATEGY 3: M15 BOLLINGER BAND 2.5 DEV MEAN REVERSION SNIPER
   // =========================================================================================
   if(isNewBar && runStrat3 && !isS3Open)
     {
      bool isTrendBuy_S3  = (ema20[1] > ema50[1]);
      bool isTrendSell_S3 = (ema50[1] > ema20[1]);
      
      // M15 Stochastic Exhaustion Safeguard (Locked to closed candle)
      bool isStochExhausted_Buy = (stochK[1] > stochD[1]);
      bool isStochExhausted_Sell = (stochK[1] < stochD[1]);
      
      // S3 BUY Setup (Elastic Snapback Pullback Reversal) + M15 Stoch Safeguard
      if(isTrendBuy_S3 && lowM15[1] < lowerBB[1] && closeM15[1] > lowerBB[1] && isStochExhausted_Buy)
        {
         double sl = NormalizeDouble(ask - (InpStopLoss * point), digits);
         double tp = NormalizeDouble(ask + (InpTakeProfit * point), digits);
         trade.SetExpertMagicNumber(InpMagic + 3);
         if(trade.Buy(InpLots, tradeSymbol, ask, sl, tp, "S3 M15 BB Snapback Buy"))
           {
            PrintFormat("📈 [OPEN S3 BUY] Price: %.3f | EMA20(M15): %.3f | EMA50(M15): %.3f | BB_Lower: %.3f | RSI(M15): %.1f | S_K(M15): %.1f | S_D(M15): %.1f", 
                        ask, currEMA20, currEMA50, lowerBB[1], currRSI, stochK[1], stochD[1]);
            isS3Open = true;
           }
        }
        
      // S3 SELL Setup (Elastic Snapback Pullback Reversal) + M15 Stoch Safeguard
      if(!isS3Open && isTrendSell_S3 && highM15[1] > upperBB[1] && closeM15[1] < upperBB[1] && isStochExhausted_Sell)
        {
         double sl = NormalizeDouble(bid + (InpStopLoss * point), digits);
         double tp = NormalizeDouble(bid - (InpTakeProfit * point), digits);
         trade.SetExpertMagicNumber(InpMagic + 3);
         if(trade.Sell(InpLots, tradeSymbol, bid, sl, tp, "S3 M15 BB Snapback Sell"))
           {
            PrintFormat("📉 [OPEN S3 SELL] Price: %.3f | EMA20(M15): %.3f | EMA50(M15): %.3f | BB_Upper: %.3f | RSI(M15): %.1f | S_K(M15): %.1f | S_D(M15): %.1f", 
                        bid, currEMA20, currEMA50, upperBB[1], currRSI, stochK[1], stochD[1]);
            isS3Open = true;
           }
        }
     }

   if(currBarTime != lastBarTime) lastBarTime = currBarTime;
   if(currBarTime_M5 != lastBarTime_M5_Trade) lastBarTime_M5_Trade = currBarTime_M5;
  }
